version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/faktory
    binary: faktory
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers_v2:
  - images:
      - quay.io/fossa/faktory
    tags:
      - "{{ .Tag }}"
    platforms:
      - linux/amd64
      - linux/arm64
    labels:
      "org.opencontainers.image.description": "Faktory, with FOSSA plugins"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"
    flags:
      - "--pull"
