before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/faktory
    binary: faktory
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - image_templates:
    - quay.io/fossa/faktory:{{ .Tag }}-amd64
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/amd64'
  - image_templates:
    - quay.io/fossa/faktory:{{ .Tag }}-arm64
    use: buildx
    build_flag_templates:
      - '--pull'
      - '--platform=linux/arm64'
    goarch: arm64
docker_manifests:
  - name_template: quay.io/fossa/faktory:{{ .Tag }}
    image_templates:
      - quay.io/fossa/faktory:{{ .Tag }}-amd64
      - quay.io/fossa/faktory:{{ .Tag }}-arm64
