ARG GO_VERSION=1.25.7
FROM golang:${GO_VERSION}-alpine

RUN apk add --no-cache redis git

WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["go", "test", "./..."]
