// Generated by ego.
// DO NOT EDIT

//line ui/layout.ego:1

package ui

import "fmt"
import "html"
import "io"
import "context"

import (
	"net/http"

	"github.com/contribsys/faktory/client"
)

func Ego_layout(w io.Writer, req *http.Request, yield func()) {

//line ui/layout.ego:12
	_, _ = io.WriteString(w, "\n<!doctype html>\n<html lang=\"eng\">\n<head>\n  <title>")
//line ui/layout.ego:15
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(client.Name)))
//line ui/layout.ego:15
	_, _ = io.WriteString(w, "</title>\n  <meta charset=\"utf8\" />\n  <link rel=\"shortcut icon\" href=\"")
//line ui/layout.ego:17
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/img/favicon.ico"))))
//line ui/layout.ego:17
	_, _ = io.WriteString(w, "\">\n  <link rel=\"mask-icon\" href=\"")
//line ui/layout.ego:18
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/img/favicon.svg"))))
//line ui/layout.ego:18
	_, _ = io.WriteString(w, "\" color=\"#000000\">\n  <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"")
//line ui/layout.ego:19
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/img/apple-touch-icon.png"))))
//line ui/layout.ego:19
	_, _ = io.WriteString(w, "\">\n  <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"")
//line ui/layout.ego:20
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/img/favicon-32x32.png"))))
//line ui/layout.ego:20
	_, _ = io.WriteString(w, "\">\n  <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"")
//line ui/layout.ego:21
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/img/favicon-16x16.png"))))
//line ui/layout.ego:21
	_, _ = io.WriteString(w, "\">\n\n  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\" />\n  <link href=\"")
//line ui/layout.ego:24
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/bootstrap.css"))))
//line ui/layout.ego:24
	_, _ = io.WriteString(w, "\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\" />\n  <link href=\"")
//line ui/layout.ego:25
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/application.css"))))
//line ui/layout.ego:25
	_, _ = io.WriteString(w, "\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\" />\n  <script type=\"text/javascript\" src=\"")
//line ui/layout.ego:26
	_, _ = io.WriteString(w, html.EscapeString(fmt.Sprint(Relative(req, "/static/application.js"))))
//line ui/layout.ego:26
	_, _ = io.WriteString(w, "\"></script>\n  <meta name=\"google\" content=\"notranslate\" />\n</head>\n<body class=\"admin d-flex flex-column\" data-locale=\"en\" data-poll-path=\"\">\n<div id=\"page\" class=\"flex-fill\">\n  <div class=\"container-xl\">\n    <div class=\"row\">\n      <div class=\"col-12\">\n        ")
//line ui/layout.ego:34
	yield()
//line ui/layout.ego:35
	_, _ = io.WriteString(w, "\n      </div>\n    </div>\n  </div>\n</div>\n</body>\n</html>\n")
//line ui/layout.ego:41
}

var _ fmt.Stringer
var _ io.Reader
var _ context.Context
var _ = html.EscapeString
