name: CI

on: [push]

permissions:
  contents: write

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Linux packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y --no-install-recommends redis-server

      - name: Install Mac packages
        if: matrix.os == 'macos-latest'
        run: brew install redis

      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          # In order:
          # * Module download cache
          # * Build cache (Linux)
          # * Build cache (Mac)
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            ~/Library/Caches/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Test
        run: go test ./...

      # Release steps
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: quay.io
          username: fossa+fossabot
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist ${{ startsWith(github.ref, 'refs/tags/') || '--snapshot' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
